milvus:
  enabled: true
  mode: standalone
  
  standalone:
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1000m"
    
    persistence:
      enabled: true
      size: 20Gi
      storageClass: ""
    
    service:
      type: ClusterIP
      ports:
        etcd: 2379
        minio: 9000
        milvus: 19530
    
    config:
      etcd:
        endpoints:
          - localhost:2379
      minio:
        address: localhost:9000 