apiVersion: v2
name: stock-news-aggregator
description: A Helm chart for Stock News Aggregator application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: "14.6.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: redis
    version: "17.15.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: milvus
    version: "4.3.3"
    repository: "https://charts.milvus.io/milvus"
    condition: milvus.enabled
  - name: backend
    version: "0.1.0"
    repository: "file://./backend"
    condition: backend.enabled
  - name: frontend
    version: "0.1.0"
    repository: "file://./frontend"
    condition: frontend.enabled 